"""Attempting to change types

Revision ID: 52a2acb8302e
Revises: bfffd6c889a3
Create Date: 2020-08-18 11:45:54.109778

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '52a2acb8302e'
down_revision = 'bfffd6c889a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('articles', 'doi',
               existing_type=mysql.VARCHAR(length=60),
               type_=sa.String(length=100),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('articles', 'doi',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=60),
               existing_nullable=True)
    # ### end Alembic commands ###
