"""Remove column file_size

Revision ID: 83412109be60
Revises: a7a97b835b79
Create Date: 2020-08-24 15:17:24.160183

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '83412109be60'
down_revision = 'a7a97b835b79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'file_size')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('file_size', mysql.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
