"""Change column types

Revision ID: 9c6fa67a1036
Revises: 52a2acb8302e
Create Date: 2020-08-18 15:23:08.613331

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9c6fa67a1036'
down_revision = '52a2acb8302e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('articles', 'doi',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=150),
               existing_nullable=True)
    op.alter_column('articles', 'elocation_id',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=150),
               existing_nullable=True)
    op.alter_column('articles', 'pii',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Text(),
               existing_nullable=True)
    op.execute('ALTER TABLE articles DROP PRIMARY KEY')
    op.alter_column('articles', 'pmid',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Integer(),
               autoincrement=False)
    op.create_primary_key(None, 'articles', ['pmid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE articles DROP PRIMARY KEY')
    op.alter_column('articles', 'pmid',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=50),
               autoincrement=False)
    op.create_primary_key(None, 'articles', ['pmid'])
    op.alter_column('articles', 'pii',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('articles', 'elocation_id',
               existing_type=sa.String(length=150),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('articles', 'doi',
               existing_type=sa.String(length=150),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
    # ### end Alembic commands ###
